sudo: required
services:
  - docker

before_install:
  - docker build -t bipindasdocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bipindasdocker/react-test npm run test

after_success:
  - docker build -t bipindasdocker/multi-client ./client
  - docker build -t bipindasdocker/multi-nginx ./nginx
  - docker build -t bipindasdocker/multi-server ./server  
  - docker build -t bipindasdocker/multi-worker ./worker
# login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to docker hub -- test
  - docker push bipindasdocker/multi-client
  - docker push bipindasdocker/multi-nginx
  - docker push bipindasdocker/multi-server
  - docker push bipindasdocker/multi-worker

# deploy: 
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "react-test"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-494270837427"
#   bucket_path: "docker-react"
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY